Ext.onReady(function()	{
	Heidi.container.Viewport = Ext.create("Ext.container.Viewport", {
		layout:"fit",
		items:[
			{
				xtype:"panel",
				title:"HeidiJS",
				iconCls:"icon-viewport-heidi-js",
				layout:"border",
				border:false,
				items:[
					{
						xtype:"toolbar",
						region:"north",
						border:false,
						items:[
							{
								text:"Test"
							}
						]
					},
					{
						xtype:"container",
						region:"center",
						layout:{
							type:"border"
						},
						border:false,
						defaults:{
							split:true
						},
						items:[
							{
								xtype:"panel",
								region:"west",
								width:250,
								html:"Connections",
								padding:"5 0 5 0"
							},
							{
								xtype:"tabpanel",
								region:"center",
								padding:"5 0 5 0",
								items:[
									{
										xtype:"panel",
										title:"Host",
										html:"host"
									}
								]
							}
						]
					},
					{
						xtype:"panel",
						region:"south",
						height:150,
						html:"test",
						resizable:true,
						dockedItems:[
							{
								xtype:"toolbar",
								dock:"bottom",
								items:[
									{
										text:"Status"
									}
								]
							}
						]
					}
				],
				dockedItems:[
					{
						xtype:"toolbar",
						dock:"top",
						items:[
							{
								text:"File"
							}
						]
					}
				]
			}
		],
		
		addConnection:function(inConnectionId)	{
	debugger;
		}
	});
});